import assert from 'node:assert/strict';
import { serialValue, agreeSerialReads, readSerialFromPhotos } from '../api/_lib/serial-photo.js';
const read=(text='033/250',side='front')=>({stampedSerial:text,stampedSerialSide:side,stampedSerialAppearance:'upper left foil stamp',isDate:false});
assert.equal(serialValue('033/250').text,'033/250');
assert.equal(serialValue('9/14/25'),null);
assert.equal(serialValue('251/250'),null);
assert.equal(agreeSerialReads([read(),read()]).den,250);
assert.equal(agreeSerialReads([read(),read('034/250')]),null);
assert.equal(agreeSerialReads([read(),read('033/250','back')]),null);
assert.equal(agreeSerialReads([read(),{...read(),isDate:true}]),null);
assert.equal(agreeSerialReads([read(),null]),null);
const crops=[],calls=[];
const crop=async(photo,box)=>{crops.push({photo,box});return photo+'-slice';};
const ask=async args=>{calls.push(args);return read();};
const out=await readSerialFromPhotos('front','back',ask,{fast:'reader-a',strong:'reader-b'},crop);
assert.equal(out.serial.text,'033/250');assert.equal(crops.length,6);assert.equal(calls.length,2);
assert.ok(calls.every(c=>c.extraImages.length===5));
assert.ok(calls.every(c=>!c.prompt.includes('Aqua')&&!c.prompt.includes('Tyler')));
const failure=await readSerialFromPhotos('front',null,async()=>{throw Error('unavailable')},{fast:'a',strong:'b'},crop);
assert.equal(failure.serial,null);
console.log('Serial photo checks passed: enlarged front/back retry, two independent readers, leading zeros, mismatched digits/sides, dates, invalid runs, and safe failure.');
