import assert from 'node:assert/strict';
import { eligibleAuction, exactTitleMatch, summarizeSales, saleKey } from '../api/_lib/sold-records.js';
import { cardsightSoldComps } from '../api/cardsight.js';
const card={name:'Tyler Shough',number:'163',set:{year:'2025',release:'2025 Topps Resurgence Football'}};
const sale=(id,price,date,title='2025 Topps Resurgence Tyler Shough #163 Aqua Surge Auto /250')=>({title,price,date,listing_type:'auction',url:`https://www.ebay.com/itm/${id}`,source:'ebay'});
const old=sale('100000000001',96,'2026-09-09'), recent=sale('100000000002',140.50,'2026-10-03');
assert.ok(exactTitleMatch(recent,card));
for(const title of [recent.title.replace('2025','2026'),recent.title.replace('163','164'),recent.title.replace('Shough','Other'),recent.title.replace('Resurgence','Chrome')]) assert.ok(!exactTitleMatch({...recent,title},card));
assert.ok(!eligibleAuction({...recent,listing_type:'fixed'}));
assert.ok(!eligibleAuction({...recent,title:recent.title+' Best offer accepted'}));
assert.ok(!eligibleAuction({...recent,date:null}));
assert.ok(!eligibleAuction({...recent,url:'javascript:alert(1)'}));
assert.equal(saleKey({...old,url:old.url+'?tracking=x'}),saleKey(old));
const summary=summarizeSales([old,recent,{...old,url:old.url+'?tracking=x'},{...recent,listing_type:'fixed',price:199.99}]);
assert.equal(summary.count,2);assert.equal(summary.mean,118.25);assert.equal(summary.items[0].date,'2026-10-03');
process.env.CARDSIGHT_API_KEY='offline-test';
let requests=[];
globalThis.fetch=async url=>{
 const u=new URL(url);requests.push(u);
 if(u.pathname==='/v1/pricing/search') return new Response(JSON.stringify({results:[recent,{...recent,url:'https://www.ebay.com/itm/100000000003',grade:{grade_id:'psa-10'}},{...recent,price:199.99,listing_type:'fixed'}]}));
 return new Response(JSON.stringify({card,raw:{records:u.searchParams.get('period')==='6m'?[old]:[]}}));
};
const result=await cardsightSoldComps('example',{parallelId:'aqua',cardIsAuto:true,parallels:[{id:'aqua',name:'Aqua Surge',numberedTo:250}]});
assert.equal(result.count,2);assert.equal(result.mean,118.25);assert.equal(result.coverage,'partial');assert.equal(result.items[0].price,140.5);
assert.ok(requests.some(u=>u.pathname==='/v1/pricing/search'&&u.searchParams.get('period')==='30d'));
assert.ok(requests.some(u=>u.pathname==='/v1/pricing/example'&&!u.searchParams.has('parallel_id')));
globalThis.fetch=async url=>{ if(new URL(url).pathname==='/v1/pricing/search') return new Response('{}',{status:503});return new Response(JSON.stringify({card,raw:{records:[old]}})); };
const fallback=await cardsightSoldComps('example',{parallelId:'aqua',cardIsAuto:true,parallels:[{id:'aqua',name:'Aqua Surge',numberedTo:250}]});
assert.equal(fallback.count,1);assert.ok(fallback.warnings.some(s=>s.includes('unavailable')));
console.log('Sold retrieval checks passed: exact identity, newest-first, deduplication, means, unknown offers, fixed asks, graded exclusions, recent title search, window retention, and provider failure fallback.');
