// GENERATED by tools/checklists/build.mjs — product registry.
import P_2025_bowman_chrome_baseball from "./2025-bowman-chrome-baseball.js";
import P_2025_donruss_optic_football from "./2025-donruss-optic-football.js";
import P_2025_panini_prizm_football from "./2025-panini-prizm-football.js";
import P_2025_topps_chrome_baseball from "./2025-topps-chrome-baseball.js";
import P_2025_topps_chrome_football from "./2025-topps-chrome-football.js";
export const PRODUCTS = [P_2025_bowman_chrome_baseball, P_2025_donruss_optic_football, P_2025_panini_prizm_football, P_2025_topps_chrome_baseball, P_2025_topps_chrome_football];
